### ISSUE TITLE
Error: An empty identity is not valid when signing a binary for the product type 'Application'. (in target 'Validator')

### ISSUE THREAD

**Issue by sargent-mg** [SwiftValidatorCommunity/SwiftValidator#221]
Hi guys:

After updating to Xcode 10.2 and Swift 5, when executing carthage update I get the following error:

**error: An empty identity is not valid when signing a binary for the product type 'Application'. (in target 'Validator')**

Try again on a new project and throw the same error.

Can someone help me please?

Best regards.

Adrián López Rendón

**Comment by jcarioti** [comment]
Same issue here. Xcode updated to 10.2 today and now this package is our only dependency that's trying (and failing) to do code signing.

**Comment by AlbertArredondoAlfaro** [comment]
Well, actually the project is not migrated to Swift 5.0. Could it be the reason?

**Comment by AlbertArredondoAlfaro** [comment]
What I do to solve the problem so far was to recompile the framework manually and overwrite the SwiftValidator.framework on the Carthage directory.

**Comment by jcarioti** [comment]
> What I do to solve the problem so far was to recompile the framework manually and overwrite the SwiftValidator.framework on the Carthage directory.

How did you recompile manually? I've pulled Albert's changes and tried Carthage update --platform iOS and I'm still getting the exact same error.

https://github.com/AlbertArredondoAlfaro/SwiftValidator/tree/swift-5.0

**Comment by AlbertArredondoAlfaro** [comment]
Hi jcarioti,

I just press Cmd+B to build the project and pick the framework generated from the Product folder.

I think that the problem with the provisioning profile should be fixed by the people in charge of the project, but I'm not sure. So far, you could use the framework the way I tell you and either wait for the PR to be accepted or fixed by the project maintainers.

Have a nice day.

**Comment by csabagyarmati** [comment]
The problem is that the project file contains the "Validator" Application in Targets.
If you delete this target from the project file, Carthage will compile is successfully.

**Comment by AlbertArredondoAlfaro** [comment]
Yes @csabagyarmati, you right. Thank you so much!

I have update the Pull Request with the @csabagyarmati fix and I also updated the travis.yml file to use Xcode 10.2.

@sargent-mg @jcarioti Now you can use Carthage update using my fork.

**Comment by pbyorke** [comment]
Albert, I am not sophisticated in Carthage, or in GitHub for that matter, but I tried putting:

github "AlbertArredondoAlfaro/SwiftValidator"

In my Cartfile, and I am still getting the empty identity error. Did I misunderstand your instructions?

**Comment by AlbertArredondoAlfaro** [comment]
Hi,

You need to specify the branch as well, like this:

github "AlbertArredondoAlfaro/SwiftValidator" "swift-5.0"

**Comment by pbyorke** [comment]
It works! Thank you so much! I have learned two good lessons, one is that I can pick a specific branch in my github statement and the other I've learned about the Issues function. I had never really even looked at it before :)
